Repository Cox-Automotive/alks-cli, pull requests merged in 2021-07, with the labels that each got.

#200 Separate tag check
  .github/workflows/build-and-test.yml
  .github/workflows/check-for-release-tag.yml
  .github/workflows/trigger-release.yml
Labels: release/skip

#202 Update `cli-color` to 2.0.0 to honor `NO_COLOR` environment variable
  README.md
  dist/package.json
  npm-shrinkwrap.json
  package.json
Labels: release/minor

#203 Manual changelog
  .github/workflows/check-for-release-tag.yml
  .github/workflows/trigger-release.yml
Labels: release/skip

#204 updates changelog.txt
  .github/workflows/check-for-release-tag.yml
  changelog.txt
  dist/changelog.txt
Labels: release/minor

#199 Shell Completion
  changelog.txt
  dist/changelog.txt
  dist/package.json
  dist/src/lib/handlers/alks-completion.js
  dist/src/lib/handlers/alks-completion.js.map
  dist/src/lib/handlers/alks-developer-configure.js
  dist/src/lib/handlers/alks-developer-configure.js.map
  dist/src/lib/handlers/alks-developer-configure.test.js
  dist/src/lib/handlers/alks-developer-configure.test.js.map
  dist/src/lib/program.js
  dist/src/lib/program.js.map
  npm-shrinkwrap.json
  package.json
  src/lib/handlers/alks-completion.ts
  src/lib/handlers/alks-developer-configure.test.ts
  src/lib/handlers/alks-developer-configure.ts
  src/lib/program.ts
  tsconfig.json
Labels: release/minor

#209 ignores the dist folder in PR diffs
  .gitattributes
Labels: release/skip

#205 Print oauth url
  changelog.txt
  dist/changelog.txt
  dist/src/lib/handlers/alks-developer-login2fa.js
  dist/src/lib/handlers/alks-developer-login2fa.js.map
  dist/src/lib/handlers/alks-sessions-console.js
  dist/src/lib/handlers/alks-sessions-console.js.map
  src/lib/handlers/alks-developer-login2fa.ts
  src/lib/handlers/alks-sessions-console.ts
Labels: release/patch

#207 Cache password
  changelog.txt
  dist/changelog.txt
  dist/src/lib/getAuth.js
  dist/src/lib/getAuth.js.map
  dist/src/lib/promptForPassword.js
  dist/src/lib/promptForPassword.js.map
  dist/src/lib/state/password.js
  dist/src/lib/state/password.js.map
  src/lib/getAuth.ts
  src/lib/promptForPassword.ts
  src/lib/state/password.ts
Labels: release/patch

#206 Env var config
  README.md
  changelog.txt
  dist/changelog.txt
  dist/src/lib/ensureConfigured.js
  dist/src/lib/ensureConfigured.js.map
  dist/src/lib/getEnvironmentVariableSecretWarning.js
  dist/src/lib/getEnvironmentVariableSecretWarning.js.map
  dist/src/lib/handlers/alks-developer-info.js.map
  dist/src/lib/state/alksAccount.js
  dist/src/lib/state/alksAccount.js.map
  dist/src/lib/state/alksRole.js
  dist/src/lib/state/alksRole.js.map
  dist/src/lib/state/outputFormat.js
  dist/src/lib/state/outputFormat.js.map
  dist/src/lib/state/password.js
  dist/src/lib/state/password.js.map
  dist/src/lib/state/server.js
  dist/src/lib/state/server.js.map
  dist/src/lib/state/token.js
  dist/src/lib/state/token.js.map
  dist/src/lib/state/userId.js
  dist/src/lib/state/userId.js.map
  src/lib/ensureConfigured.ts
  src/lib/getEnvironmentVariableSecretWarning.ts
  src/lib/handlers/alks-developer-info.ts
  src/lib/state/alksAccount.ts
  src/lib/state/alksRole.ts
  src/lib/state/outputFormat.ts
  src/lib/state/password.ts
  src/lib/state/server.ts
  src/lib/state/token.ts
  src/lib/state/userId.ts
Labels: release/minor

#208 Options
  changelog.txt
  dist/changelog.txt
  dist/src/lib/getAlksAccounts.js
  dist/src/lib/getAlksAccounts.js.map
  dist/src/lib/handlers/alks-developer-configure.js
  dist/src/lib/handlers/alks-developer-configure.js.map
  dist/src/lib/handlers/alks-developer-configure.test.js
  dist/src/lib/handlers/alks-developer-configure.test.js.map
  dist/src/lib/handlers/alks-developer-login2fa.js
  dist/src/lib/handlers/alks-developer-login2fa.js.map
  dist/src/lib/program.js
  dist/src/lib/program.js.map
  dist/src/lib/promptForAlksAccountAndRole.js
  dist/src/lib/promptForAlksAccountAndRole.js.map
  dist/src/lib/promptForAuthType.js
  dist/src/lib/promptForAuthType.js.map
  dist/src/lib/promptForToken.js
  dist/src/lib/promptForToken.js.map
  dist/src/lib/state/password.js
  dist/src/lib/state/password.js.map
  dist/src/lib/validateAlksAccount.js
  dist/src/lib/validateAlksAccount.js.map
  src/lib/getAlksAccounts.ts
  src/lib/handlers/alks-developer-configure.test.ts
  src/lib/handlers/alks-developer-configure.ts
  src/lib/handlers/alks-developer-login2fa.ts
  src/lib/program.ts
  src/lib/promptForAlksAccountAndRole.ts
  src/lib/promptForAuthType.ts
  src/lib/promptForToken.ts
  src/lib/state/password.ts
  src/lib/validateAlksAccount.ts
Labels: release/minor

#210 Fix same day builds
  .github/workflows/trigger-release.yml
  changelog.txt
  dist/changelog.txt
Labels: release/minor

#211 typo
  .github/workflows/trigger-release.yml
  changelog.txt
  dist/changelog.txt
Labels: release/minor
